### ISSUE TITLE
Create DroneKit init function

### ISSUE THREAD

**Issue by lwreinert** [LPRDev/RoverSentry#1]
Create a program that initializes  [Dronekit](http://python.dronekit.io/guide/connecting_vehicle.html):
- Creates necessary objects (e.g. vehicle). 
- Sets communication port to APM (USB).
- Tests the connection to the APM/ArduPilot.
-  Returns (pass/fail) status to the caller.

**Comment by petercr19** [comment]
New python file dronekit_init.py. Includes a class containing html accessible methods and another class for handling startup for the APM module.
