### ISSUE TITLE
Add Max Sonar Sensor

### ISSUE THREAD

**Issue by lwreinert** [LPRDev/RoverSentry#8]
The [LV-MaxSonar-EZ4](https://github.com/LPRDev/RoverSentry/wiki/sensors) is supported by Ardupilot. The MaxSonar sensor needs to be mounted on the RoverSentry and wired via the [RangeFinder](http://planner.ardupilot.com/wp-content/uploads/sites/5/2014/08/RangeFinder_MaxbotixAnalog_APM2.jpg) Wire diagram.

**Comment by petercr19** [comment]
Mounted on front. Wired to APM module. APM will handle sensor.
